import { useState, useEffect } from 'react'
import { Film, Star, TrendingUp, Clock, PlayCircle } from 'lucide-react'
import movieData from './data/movies.json'
import './App.css'

function App() {
  return (
    <div className="min-h-screen bg-[#050505] text-white font-sans selection:bg-cyan-500/30">
      {/* Navbar */}
      <nav className="fixed w-full top-0 z-50 bg-[#050505]/80 backdrop-blur-md border-b border-white/10 px-8 py-4 flex justify-between items-center">
        <div className="flex items-center gap-2 text-2xl font-bold">
          <Film className="text-cyan-400" />
          <span>Neo<span className="text-cyan-400 font-light">Critics</span></span>
        </div>
        <div className="flex gap-6 text-sm font-semibold tracking-wider text-gray-400">
          <a href="#" className="text-white hover:text-cyan-400 transition">DISCOVER</a>
          <a href="#" className="hover:text-cyan-400 transition">REVIEWS</a>
          <a href="#" className="hover:text-cyan-400 transition">CRITICS</a>
        </div>
      </nav>

      {/* Hero Section */}
      <main className="pt-32 px-8 max-w-7xl mx-auto flex flex-col md:flex-row items-center gap-12">
        <div className="flex-1 space-y-6">
          <div className="inline-block px-4 py-1 rounded-full border border-rose-500/50 bg-rose-500/10 text-rose-400 text-xs font-bold tracking-widest">
            POWERED BY PYTHON & REACT
          </div>
          <h1 className="text-6xl font-black tracking-tight leading-tight">
            AI-DRIVEN <br/> MOVIE INSIGHTS
          </h1>
          <p className="text-gray-400 text-lg leading-relaxed max-w-lg">
            Experience the next generation of film critique. Our Python backend analyzes trends in real-time, delivered instantly via our lightning-fast React architecture.
          </p>
          <div className="flex gap-4 pt-4">
            <button className="bg-cyan-400 text-black px-8 py-3 rounded-lg font-bold flex items-center gap-2 hover:bg-cyan-300 transition hover:scale-105">
              <PlayCircle size={20} /> Watch Trailer
            </button>
            <button className="bg-white/5 border border-white/10 px-8 py-3 rounded-lg font-bold hover:bg-white/10 transition">
              Read Analysis
            </button>
          </div>
        </div>
        <div className="flex-1 w-full relative">
          <div className="absolute inset-0 bg-cyan-500/20 blur-[100px] rounded-full" />
          <img 
            src="https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800" 
            alt="Cinematic"
            className="relative z-10 w-full rounded-2xl border border-white/10 shadow-2xl shadow-black/50 hover:scale-[1.02] transition duration-500"
          />
        </div>
      </main>

      {/* Dynamic Python Data Section */}
      <section className="mt-32 px-8 max-w-7xl mx-auto pb-32">
        <div className="flex items-center gap-3 mb-10">
          <TrendingUp className="text-rose-500" size={32} />
          <h2 className="text-3xl font-bold">Trending Live Data</h2>
        </div>
        
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {movieData.movies.map(movie => (
            <div key={movie.id} className="bg-white/5 border border-white/10 p-6 rounded-xl hover:bg-white/10 transition group cursor-pointer">
              <div className="flex justify-between items-start mb-4">
                <span className="bg-cyan-500/20 text-cyan-400 px-3 py-1 rounded-full text-xs font-bold">
                  {movie.genre}
                </span>
                <span className="flex items-center gap-1 text-yellow-500 font-bold">
                  <Star size={16} fill="currentColor" /> {movie.rating}
                </span>
              </div>
              <h3 className="text-xl font-bold mb-2 group-hover:text-cyan-400 transition">{movie.title}</h3>
              <p className="text-gray-500 text-sm flex items-center gap-2">
                <Clock size={14} /> Trend Score: {movie.trend_score}
              </p>
            </div>
          ))}
        </div>
        
        <div className="mt-8 text-center text-gray-500 text-sm">
          Data automatically generated by Python analyzer at {new Date(movieData.generated_at).toLocaleString()}
        </div>
      </section>
    </div>
  )
}

export default App
